### ISSUE TITLE
Implement switch to disableRequireCodeChallengeForPublicClients().

### ISSUE THREAD

**Issue by millemedia** [r3h6/TYPO3.EXT.oauth2_server#3]
Hi Remo,

can you please integrate a switch to disable requireCodeChallengeForPublicClients in AuthCodeGrant? 

If you can disable this, with call of function disableRequireCodeChallengeForPublicClients(). Than also oauth2 w/o PKCE code challenge will be possible.

Kind regards

Andreas

**Comment by r3h6** [comment]
Please try and test the new configuration "[requireCodeChallengeForPublicClients](https://github.com/r3h6/TYPO3.EXT.oauth2_server/blob/feature/3/README.md)" in the branch "[feature/3](https://packagist.org/packages/r3h6/oauth2-server#dev-feature/3)".
If its working I will publish a new release to the TER.

**Comment by millemedia** [comment]
Hi Remo,
just tested it. It works.
Kind regards
Andreas

**Comment by r3h6** [comment]
Available in v1.1.1
